### ISSUE TITLE
Bower Issues

### ISSUE THREAD

**Issue by crederaken** [scriptwerx/angular-swx-session-storage#2]
I am currently getting the following:

ENOTFOUND Package Angular-swx-session-storage ($sessionStorage)=angular-swx-session-storage not found

running a bower update

**Comment by theDustRoom** [comment]
I've updated both _angular-swx-session-storage_ and _angular-swx-local-storage_ to v1.0.2.

I think there's an issue with the naming of the packages so they've been changed/updated.

You'll have to edit your _bower.json_ file and delete the entry for this package.

Then clean your bower cache:

`bower cache clean`

And then re-install this package:

`bower install angular-swx-session-storage --save-dev`

That should correct the issue.
