### ISSUE TITLE
key expire when set a fraction of a day

### ISSUE THREAD

**Issue by DiV666** [scriptwerx/angular-swx-session-storage#3]
Hi,

Thanks for your $sessionStorage service.

I need to set the expiration time to 20 minutes, but when setting this to less than a day, the key disappears when refreshing the page.

Ej:
```
var minuteByDay = 0.000694444444; //=> (1 minute)
$sessionStorage.put('key', 'data', 2); //=> OK
$sessionStorage.put('key', 'data', 1 / 24); //=> Remove on refresh
$sessionStorage.put('key', 'data', minuteByDay); //=> Remove on refresh
$sessionStorage.put('key', 'data', minuteByDay * 20); //=> Remove on refresh
```

Could you tell me why this happens?

Thank you.

**Comment by theDustRoom** [comment]
I'll look into it.

**Comment by theDustRoom** [comment]
Ah; sorry.

The README is incorrect expiry is set in minutes not days.

Sorry about that; I'll update the README.

**Comment by DiV666** [comment]
Don't worry,

Thanks for your quick response.

**Comment by deshario** [comment]
I think this is how you should set an expiration date for 24 hr ```$sessionStorage.put(key, value, 1440);```
@DiV666 @theDustRoom Am I right ?

**Comment by theDustRoom** [comment]
Hey @deshario you are correct, 24 hours would be 60 * 24 which is 1440.
